name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Restore dependencies
      run: dotnet restore dirs.proj
    - name: Build
      run: dotnet build dirs.proj --framework net8.0 --configuration Debug
    - name: Test
      run: dotnet test dirs.proj --framework net8.0 --no-build --verbosity normal
